import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { computeEffectsDigest, computePacketId, COMPARATOR_CONTRACT_VERSION } from "./migrationAuditComparator";

/**
 * Guards the checked-in EXPECTED catalog manifest + provenance graph (Slice 3.2I-R5B1A.1-R2.2).
 * The manifest is REGENERATED by `npm run build:foundry-migration-manifest` (disposable Postgres);
 * this test guards its structural integrity + provenance correctness so it cannot silently drift.
 */
const AUDIT_DIR = join(process.cwd(), "docs/audit");
const manifest = JSON.parse(readFileSync(join(AUDIT_DIR, "foundry_migration_expected_catalog.json"), "utf8"));
const provenance = JSON.parse(readFileSync(join(AUDIT_DIR, "foundry_migration_provenance.json"), "utf8"));

describe("expected catalog manifest — integrity + reproducibility pointer", () => {
  it("declares how to regenerate itself and which audit query produced it", () => {
    expect(manifest.regenCommand).toContain("build-expected-manifest.sh");
    expect(manifest.auditQuery).toBe("docs/audit/foundry_migration_provenance_readonly.sql");
    expect(manifest.postgresServerVersionNum).toBeGreaterThan(150000);
  });

  it("effectCount matches the effects array; every effect is well-formed", () => {
    expect(manifest.effectCount).toBe(manifest.effects.length);
    expect(manifest.effects.length).toBeGreaterThan(50);
    for (const e of manifest.effects) {
      expect(e.effectId).toBeTruthy();
      expect(["column", "table", "pk", "fk", "unique", "check", "index", "function", "rls", "policies", "acl_table", "acl_function"]).toContain(e.objectType);
      expect(["structured", "structured+digest", "structured+body_digest"]).toContain(e.comparisonMode);
      expect(e.migrationVersion).toMatch(/^2026072[6789]000000$/); // introduction is never rewritten
      expect(e.finalAuthorityMigration).toMatch(/^(2026072[6789]|20260804)000000$/);
    }
  });

  it("covers every audited object category incl. first-class PK/FK/UNIQUE/CHECK + ACL", () => {
    const ids = new Set(manifest.effects.map((e: { effectId: string }) => e.effectId));
    const types = new Set(manifest.effects.map((e: { objectType: string }) => e.objectType));
    expect(ids.has("table:public.foundry_participant_followups")).toBe(true);
    expect(ids.has("index:public.foundry_followups_owner_due_idx")).toBe(true);
    expect([...ids].some((i) => String(i).startsWith("function:public.bty_foundry_submit_followup"))).toBe(true);
    for (const t of ["pk", "fk", "unique", "check", "rls", "policies", "acl_function", "acl_table"]) expect(types.has(t)).toBe(true);
  });

  it("R2.6 — the release-authority manifest is built on the LIVE PostgreSQL major (17)", () => {
    // A PostgreSQL-16 digest cannot authoritatively judge PostgreSQL 17: with a cross-major packet
    // every digest-mode effect degrades to MANUAL and no migration can reach a clean verdict.
    expect(Math.floor(manifest.postgresServerVersionNum / 10000)).toBe(17);
  });

  it("R2.7 — build metadata: compile-on, r2.7 schema, integrity digest + packetId + runtime digest", () => {
    expect(manifest.functionBodyChecking).toBe("on");
    expect(manifest.auditSchemaVersion).toBe("r2.7");
    expect(manifest.auditPacketVersion).toBe("r2.7");
    expect(manifest.runtimeQueryContractVersion).toBe("r2.7");
    expect(manifest.comparatorContractVersion).toBe(COMPARATOR_CONTRACT_VERSION);
    expect(computeEffectsDigest(manifest.effects)).toBe(manifest.expectedManifestDigest);
    expect(manifest.packetId).toMatch(/^[0-9a-f]{64}$/);
    expect(manifest.expectedRuntimeQueryDigest).toMatch(/^[0-9a-f]{64}$/);
  });

  it("R2.7 — packetId is reproducible from the checked-in component digests (self-authenticating)", () => {
    const shaFile = (p: string) => createHash("sha256").update(readFileSync(join(process.cwd(), p))).digest("hex");
    const MIG = "supabase/migrations";
    const migrationChecksums: Record<string, string> = {
      "20260726000000": shaFile(`${MIG}/20260726000000_foundry_shared_understanding_v1.sql`),
      "20260727000000": shaFile(`${MIG}/20260727000000_personalize_today_from_reflections_v1.sql`),
      "20260728000000": shaFile(`${MIG}/20260728000000_foundry_participant_followups_v1.sql`),
      "20260729000000": shaFile(`${MIG}/20260729000000_foundry_submit_followup_ambiguity_fix_v1.sql`),
      "20260804000000": shaFile(`${MIG}/20260804000000_foundry_function_body_reconciliation_v1.sql`),
    };
    expect(manifest.migrationChecksums).toEqual(migrationChecksums);
    expect(manifest.auditQueryBodyDigest).toBe(shaFile("scripts/migration-proof/audit-query-body.sql"));
    expect(manifest.provenanceDigest).toBe(shaFile("docs/audit/foundry_migration_provenance.json"));
    expect(manifest.securityStatementMapDigest).toBe(shaFile("docs/audit/foundry_migration_security_statement_map.json"));
    expect(manifest.constraintStatementMapDigest).toBe(shaFile("docs/audit/foundry_migration_constraint_statement_map.json"));
    const base = {
      auditSchemaVersion: manifest.auditSchemaVersion, auditPacketVersion: manifest.auditPacketVersion,
      runtimeQueryContractVersion: manifest.runtimeQueryContractVersion, comparatorContractVersion: manifest.comparatorContractVersion,
      expectedManifestDigest: manifest.expectedManifestDigest, provenanceDigest: manifest.provenanceDigest,
      securityStatementMapDigest: manifest.securityStatementMapDigest, constraintStatementMapDigest: manifest.constraintStatementMapDigest,
      auditQueryBodyDigest: manifest.auditQueryBodyDigest, expectedRuntimeQueryDigest: manifest.expectedRuntimeQueryDigest, migrationChecksums,
    };
    expect(computePacketId(base)).toBe(manifest.packetId);
  });

  it("R2.7 — the generated audit SQL is ONE statement that measures the executed query", () => {
    const sql = readFileSync(join(process.cwd(), "docs/audit/foundry_migration_provenance_readonly.sql"), "utf8");
    expect(sql).toContain("GENERATED — do not hand-edit");
    expect(sql).toContain(`'packetId', '${manifest.packetId}'`);
    expect(sql).toContain(`'expectedRuntimeQueryDigest', '${manifest.expectedRuntimeQueryDigest}'`);
    expect(sql).toContain("current_query()"); // measures the actual statement
    expect(sql).toContain("actualRuntimeQueryDigest");
    // Exactly one executable statement (Gate 2): strip comments, exactly one terminating ';'.
    const noComments = sql.replace(/--[^\n]*/g, "").replace(/\/\*[\s\S]*?\*\//g, "");
    expect((noComments.match(/;/g) ?? []).length).toBe(1);
  });

  it("R2.7 — privileges are EXACT ACL tuples; FK is a full behavioral contract", () => {
    const facl = manifest.effects.find((e: { objectType: string }) => e.objectType === "acl_function");
    expect(facl.properties.tuples).toEqual([{ grantee: "service_role", grantable: false, privilege: "EXECUTE" }]);
    const fk = manifest.effects.find((e: { objectType: string }) => e.objectType === "fk");
    for (const k of ["sourceColumns", "refTable", "refColumns", "onUpdate", "onDelete", "matchType", "deferrable", "validated"]) {
      expect(fk.properties).toHaveProperty(k);
    }
  });
});

describe("statement maps — exact source provenance (Gates 7–8)", () => {
  const smap = JSON.parse(readFileSync(join(AUDIT_DIR, "foundry_migration_security_statement_map.json"), "utf8"));
  const cmap = JSON.parse(readFileSync(join(AUDIT_DIR, "foundry_migration_constraint_statement_map.json"), "utf8"));
  const ids = new Set(manifest.effects.map((e: { effectId: string }) => e.effectId));
  const hex = /^[0-9a-f]{64}$/;

  it("security statements carry exact source SHA-256 + line, and resolve to real effects", () => {
    expect(smap.statements.length).toBe(16);
    for (const s of smap.statements) {
      expect(s.sourceSha256).toMatch(hex);
      expect(typeof s.startLine).toBe("number");
      expect(["GRANT_TABLE", "GRANT_FUNCTION", "REVOKE_TABLE", "REVOKE_FUNCTION", "RLS_ENABLE", "RLS_FORCE", "RLS_DISABLE", "CREATE_POLICY", "ALTER_POLICY", "DROP_POLICY", "ALTER_OWNER", "ALTER_DEFAULT_PRIVILEGES"]).toContain(s.statementType);
      for (const id of s.effectIds) expect(ids.has(id)).toBe(true);
    }
  });

  it("every acl/rls effect has ≥1 source security statement (policies are absence-assertions)", () => {
    const mapped = new Set(smap.statements.flatMap((s: { effectIds: string[] }) => s.effectIds));
    for (const e of manifest.effects.filter((x: { objectType: string }) => ["acl_function", "acl_table", "rls"].includes(x.objectType))) {
      expect(mapped.has(e.effectId)).toBe(true);
    }
  });

  it("every PK/FK/UNIQUE/CHECK effect has exact source-statement provenance", () => {
    const conEffectIds = new Set(manifest.effects.filter((e: { objectType: string }) => ["pk", "fk", "unique", "check"].includes(e.objectType)).map((e: { effectId: string }) => e.effectId));
    const mapped = new Set(cmap.statements.map((s: { effectId: string }) => s.effectId));
    expect(mapped).toEqual(conEffectIds); // one mapping per constraint effect, exactly
    for (const s of cmap.statements) {
      expect(s.sourceSha256).toMatch(hex);
      expect(["named", "inline_create_table"]).toContain(s.sourceKind);
      expect(s.migrationVersion).toMatch(/^2026072[68]000000$/);
    }
  });
});

describe("R2.6 — ACL authority boundary (only statement-controlled tuples are compared)", () => {
  const smap = JSON.parse(readFileSync(join(AUDIT_DIR, "foundry_migration_security_statement_map.json"), "utf8"));
  const aclEffects = manifest.effects.filter((e: { objectType: string }) => ["acl_table", "acl_function"].includes(e.objectType));

  it("every ACL effect declares a controlled-role scope and a separate diagnostic channel", () => {
    expect(aclEffects.length).toBe(7);
    for (const e of aclEffects) {
      expect(Array.isArray(e.properties.controlledRoles)).toBe(true);
      expect(Array.isArray(e.properties.tuples)).toBe(true);
      expect(Array.isArray(e.properties.environmentTuples)).toBe(true);
    }
  });

  it("the declared scope EQUALS the roles the migration statements actually control (derived, not asserted)", () => {
    // The boundary must come from the tokenized GRANT/REVOKE statements, so it can be neither
    // widened nor narrowed to make a result pass.
    for (const e of aclEffects) {
      expect(smap.aclAuthorityScope[e.effectId]).toEqual(e.properties.controlledRoles);
    }
  });

  it("TABLE authority covers PUBLIC/anon/authenticated only — service_role is never granted or revoked on these tables", () => {
    // The only table privilege statement in the audited migrations is
    //   revoke all on public.<t> from anon, public, authenticated;
    // There is no table GRANT at all, so service_role sits outside migration authority.
    const tableStmts = smap.statements.filter((s: { statementType: string }) => s.statementType.endsWith("_TABLE"));
    expect(tableStmts.length).toBe(3);
    for (const s of tableStmts) {
      expect(s.statementType).toBe("REVOKE_TABLE");
      expect(s.roles.slice().sort()).toEqual(["anon", "authenticated", "public"]);
    }
    for (const e of manifest.effects.filter((x: { objectType: string }) => x.objectType === "acl_table")) {
      expect(e.properties.controlledRoles).toEqual(["PUBLIC", "anon", "authenticated"]);
      expect(e.properties.tuples).toEqual([]); // revoked → no explicit controlled tuple survives
    }
  });

  it("FUNCTION authority additionally covers service_role — it IS explicitly granted EXECUTE", () => {
    for (const e of manifest.effects.filter((x: { objectType: string }) => x.objectType === "acl_function")) {
      expect(e.properties.controlledRoles).toEqual(["PUBLIC", "anon", "authenticated", "service_role"]);
      expect(e.properties.tuples).toEqual([{ grantee: "service_role", grantable: false, privilege: "EXECUTE" }]);
      expect(e.properties.environmentTuples).toEqual([]); // no Supabase role outside function authority
    }
  });

  it("the audit query itself carries the authority boundary (so live and expected can never diverge)", () => {
    const body = readFileSync(join(process.cwd(), "scripts/migration-proof/audit-query-body.sql"), "utf8");
    expect(body).toContain(`'["PUBLIC","anon","authenticated"]'::jsonb`);
    expect(body).toContain(`'["PUBLIC","anon","authenticated","service_role"]'::jsonb`);
    expect(body).toContain("'environmentTuples'");
  });
});

describe("R2.8 — the 20260804 reconciliation migration is FINAL body authority", () => {
  const RECON = "supabase/migrations/20260804000000_foundry_function_body_reconciliation_v1.sql";
  const sql = readFileSync(join(process.cwd(), RECON), "utf8");
  const fnEffect = (name: string) =>
    manifest.effects.find((e: { objectType: string; effectId: string }) => e.objectType === "function" && e.effectId.startsWith(`function:public.${name}(`));

  it("both drifted bodies now resolve to 20260804 WITHOUT rewriting where they were introduced", () => {
    const ssr = fnEffect("bty_foundry_set_shared_review");
    expect(ssr.migrationVersion).toBe("20260726000000"); // introduction preserved
    expect(ssr.finalAuthorityMigration).toBe("20260804000000");
    const sf = fnEffect("bty_foundry_submit_followup");
    expect(sf.migrationVersion).toBe("20260728000000"); // introduction preserved
    expect(sf.finalAuthorityMigration).toBe("20260804000000");
  });

  it("the untouched functions keep their original authority", () => {
    expect(fnEffect("bty_foundry_materialize_followup").finalAuthorityMigration).toBe("20260728000000");
    expect(fnEffect("bty_foundry_get_my_followup").finalAuthorityMigration).toBe("20260728000000");
  });

  it("ACL authority does NOT move — the migration grants and revokes nothing", () => {
    const acl = (name: string) => manifest.effects.find((e: { objectType: string; effectId: string }) =>
      e.objectType === "acl_function" && e.effectId.startsWith(`acl:function:public.${name}(`));
    expect(acl("bty_foundry_set_shared_review").finalAuthorityMigration).toBe("20260726000000");
    expect(acl("bty_foundry_submit_followup").finalAuthorityMigration).toBe("20260729000000");
    expect(sql).not.toMatch(/^\s*(grant|revoke)\b/im);
  });

  it("the expected body digests are the reconciled ones", () => {
    // set_shared_review is the 20260726 body reinstated verbatim — its digest must NOT change.
    expect(fnEffect("bty_foundry_set_shared_review").definitionDigest).toBe("ea74856969177950a0c6e59fd1dc2fd766f4161b1289f360bc22d61980bc2af9");
    expect(fnEffect("bty_foundry_submit_followup").definitionDigest).toBe("4826ad0d0359719b67433a131c5595c1402067259f2294bcfb6da9f08ef47b59");
  });

  it("carries the fall-through fix: the RESPONDED branch terminates explicitly", () => {
    // The defect was `return query …` with no `return;`, so PL/pgSQL fell through into the UPDATE.
    const branch = /if v_row\.status = 'RESPONDED' then([\s\S]*?)end if;/.exec(sql);
    expect(branch).not.toBeNull();
    expect(branch![1]).toContain("'unchanged'");
    expect(branch![1]).toContain("'already_responded'");
    // the `return;` immediately after the inner if/else, before the UPDATE
    expect(sql).toMatch(/end if;\s*\n\s*return;\s*\n\s*end if;/);
  });

  it("preserves the 20260729 ambiguity correction and the security contract", () => {
    expect(sql).toContain("#variable_conflict use_column");
    expect((sql.match(/security definer/g) ?? []).length).toBe(2);
    expect((sql.match(/set search_path = pg_catalog, public/g) ?? []).length).toBe(2);
  });

  it("touches ONLY the two function bodies — no table/column/policy/index change", () => {
    const executable = sql.replace(/--[^\n]*/g, "").replace(/\/\*[\s\S]*?\*\//g, "");
    expect(executable).not.toMatch(/\b(create|alter|drop)\s+(table|index|policy|type|schema)\b/i);
    expect((executable.match(/create or replace function/g) ?? []).length).toBe(2);
  });
});

describe("provenance — final authority follows the whole migration chain", () => {
  it("each function's final authority is the LAST migration that redefines it", () => {
    const fn = (n: string) => manifest.effects.find((e: { objectType: string; effectId: string }) =>
      e.objectType === "function" && e.effectId.startsWith(`function:public.${n}`));

    // Reconciled by 20260804 (R2.8) — introduction still records where each first appeared.
    expect(fn("bty_foundry_submit_followup").migrationVersion).toBe("20260728000000");
    expect(fn("bty_foundry_submit_followup").finalAuthorityMigration).toBe("20260804000000");
    expect(fn("bty_foundry_set_shared_review").migrationVersion).toBe("20260726000000");
    expect(fn("bty_foundry_set_shared_review").finalAuthorityMigration).toBe("20260804000000");

    // Never redefined — authority stays with the introducing migration.
    expect(fn("bty_foundry_materialize_followup").finalAuthorityMigration).toBe("20260728000000");
    expect(fn("bty_foundry_get_my_followup").finalAuthorityMigration).toBe("20260728000000");
  });

  it("provenance graph agrees with the manifest on exactly which objects were modified", () => {
    const modified = provenance.objects.filter((o: { modifiedBy: string[] }) => o.modifiedBy.length > 0);
    expect(modified.map((o: { id: string }) => o.id).sort()).toEqual([
      "function:public.bty_foundry_set_shared_review(uuid,uuid,uuid,text,text)",
      "function:public.bty_foundry_submit_followup(uuid,uuid,text)",
    ]);
    const by = Object.fromEntries(modified.map((o: { id: string; modifiedBy: string[]; finalAuthorityMigration: string }) =>
      [o.id.includes("submit_followup") ? "submit" : "review", o]));
    // submit_followup was corrected twice: 42702 ambiguity, then the fall-through defect.
    expect(by.submit.modifiedBy).toEqual(["20260729000000", "20260804000000"]);
    expect(by.submit.finalAuthorityMigration).toBe("20260804000000");
    expect(by.review.modifiedBy).toEqual(["20260804000000"]);
    expect(by.review.finalAuthorityMigration).toBe("20260804000000");

    // Provenance and manifest must not disagree about final authority.
    for (const o of modified) {
      const name = o.id.slice("function:public.".length).split("(")[0];
      const eff = manifest.effects.find((e: { objectType: string; effectId: string }) =>
        e.objectType === "function" && e.effectId.startsWith(`function:public.${name}(`));
      expect(eff.finalAuthorityMigration).toBe(o.finalAuthorityMigration);
    }
  });
});
