/**
 * R2.54 RUNNER EXECUTABLE BINDING (Slice 3.2I-R5B1A.1-R2.54).
 *
 * R2.51 measured every content digest in the manifest matching while the code they described was
 * unreachable. The counterpart failure for a RUNNER is a canary generated by a script nobody runs, a
 * manifest naming a path that no longer exists, or a preparation mode that quietly does nothing.
 *
 * These tests resolve the bound path, invoke its preparation mode for real, and read the generated
 * canary back. Nothing here calls a provider, reads a credential, touches a database or executes the
 * live replay — the preparation path stops well before any of that, and one of the assertions is
 * precisely that it does.
 */

import { describe, it, expect } from "vitest";
import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { BOUNDARY_REPLAY_RUNNER_PATH, buildContractManifest, canonicalJson } from "./contractManifest";
import { FIELD_REPAIR_OBSERVABILITY_VERSION, FIELD_REPAIR_VALUE_MAX, prerequisiteClosure } from "@/domain/foundry/arena-draft/boundaryFieldRepair";
import { NARROW_REPLAY_ARTIFACT_VERSION } from "@/domain/foundry/arena-draft/boundaryOutcomes";
import { groupAlternativeContractSha256 } from "@/domain/foundry/arena-draft/boundaryGroupAlternatives";
import { R252_LIVE_ARTIFACT_SHA256 } from "@/domain/foundry/arena-draft/r252LiveDtoFixture";

const REPO = process.cwd();
const RUNNER = join(REPO, BOUNDARY_REPLAY_RUNNER_PATH);

/** One preparation invocation, shared. `--binding-json` is the mode that proves imports resolve. */
let binding: Record<string, unknown> | null = null;
const bindingJson = (): Record<string, unknown> => {
  binding ??= JSON.parse(execFileSync("npx", ["--yes", "tsx", BOUNDARY_REPLAY_RUNNER_PATH, "--binding-json"], { cwd: REPO, encoding: "utf8" })) as Record<
    string,
    unknown
  >;
  return binding;
};

describe("[R2.54] the manifest names a runner that exists and runs", () => {
  it("the manifest carries the runner binding, and it moves with the path", () => {
    const m = buildContractManifest("a".repeat(40), "gpt-4o-mini") as unknown as Record<string, unknown>;
    const serialized = canonicalJson(m);
    expect(serialized).toContain("boundaryReplayRunnerBinding");
    // The digest is over the path among other facts, so a renamed runner cannot keep the same binding.
    expect(BOUNDARY_REPLAY_RUNNER_PATH).toBe("scripts/practice-c18-canonical-alternative-replay-runner.ts");
  });

  it("the bound path RESOLVES to a tracked, executable-mode file", () => {
    expect(existsSync(RUNNER), RUNNER).toBe(true);
    const st = statSync(RUNNER);
    expect(st.isFile()).toBe(true);
    expect(st.size).toBeGreaterThan(0);
    // The repository convention for a runner: a tsx shebang, invoked through npx.
    expect(readFileSync(RUNNER, "utf8").startsWith("#!/usr/bin/env npx tsx")).toBe(true);
  });

  it("no DEPRECATED or shadow runner is selected", () => {
    // The earlier runners are retained as history and must not be the bound one.
    for (const shadow of ["scripts/practice-c18-field-repair-replay-runner.ts", "scripts/practice-c18-repair-routing-replay-runner.ts"]) {
      expect(BOUNDARY_REPLAY_RUNNER_PATH).not.toBe(shadow);
    }
    // And the bound runner generates its own canary, not another script's.
    expect(readFileSync(RUNNER, "utf8")).toContain(BOUNDARY_REPLAY_RUNNER_PATH);
  });
});

describe("[R2.54] the preparation mode invokes the intended code", () => {
  it("`--binding-json` runs, so every import in the bound runner resolves", () => {
    const b = bindingJson();
    expect(typeof b.head).toBe("string");
    expect((b.head as string)).toHaveLength(40);
    expect((b.manifestSha256 as string)).toHaveLength(64);
  });

  it("the binding carries the R2.54 authorities, recomputed from source and not restated", () => {
    const b = bindingJson();
    // Each of these is compared against the value the DOMAIN produces right now. A runner that had
    // frozen a stale copy would fail here rather than at a live run.
    expect(b.groupAlternativeAuthoritySha256).toBe(groupAlternativeContractSha256());
    expect(b.fieldRepairObservabilityVersion).toBe(FIELD_REPAIR_OBSERVABILITY_VERSION);
    expect(b.writtenReplayArtifactVersion).toBe(NARROW_REPLAY_ARTIFACT_VERSION);
    expect(b.fieldRepairValueMax).toBe(FIELD_REPAIR_VALUE_MAX);
    expect(b.prerequisiteClosureSize).toBe(prerequisiteClosure().length);
    expect(b.prerequisiteClosureIncludesReason).toBe(true);
    expect(b.reasonIsRepairable).toBe(true);
    expect(b.capturedR252ArtifactSha256).toBe(R252_LIVE_ARTIFACT_SHA256);
    // The deferral is bound too, so a green canary cannot quietly stop saying it.
    expect(b.classifierForensicDeferred).toBe(true);
    expect(b.classifyTruthStateModifiedByThisSlice).toBe(false);
  });

  it("`--out` writes an executable canary that is valid shell", () => {
    const dir = mkdtempSync(join(tmpdir(), "r254-runner-"));
    try {
      const out = join(dir, "canary.sh");
      execFileSync("npx", ["--yes", "tsx", BOUNDARY_REPLAY_RUNNER_PATH, "--out", out], { cwd: REPO, encoding: "utf8" });
      expect(existsSync(out)).toBe(true);
      expect(statSync(out).mode & 0o100).toBeGreaterThan(0); // owner-executable
      execFileSync("bash", ["-n", out], { cwd: REPO }); // throws on a syntax error
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe("[R2.54] artifact /6 is reachable through the bound preparation path", () => {
  const canary = (): string => {
    const dir = mkdtempSync(join(tmpdir(), "r254-canary-"));
    try {
      const out = join(dir, "canary.sh");
      execFileSync("npx", ["--yes", "tsx", BOUNDARY_REPLAY_RUNNER_PATH, "--out", out], { cwd: REPO, encoding: "utf8" });
      return readFileSync(out, "utf8");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  };

  it("the canary runs the replay program and reads the observability record back", () => {
    const s = canary();
    expect(s).toContain("scripts/practice-c18-narrow-boundary-replay.ts");
    expect(s).toContain("fieldRepairObservability");
    expect(s).toContain(FIELD_REPAIR_OBSERVABILITY_VERSION);
    expect(s).toContain(NARROW_REPLAY_ARTIFACT_VERSION);
    // The two acceptance questions R2.52's canary could not ask.
    expect(s).toContain("MERGE BOUNDARY CROSSED");
    expect(s).toContain("MERGE BOUNDARY NOT CROSSED");
  });

  it("both legs exist: the canonical alternative, and the captured R2.52 refusal", () => {
    const s = canary();
    expect(s).toContain("--mock-outcome 'incomplete-field-repair'");
    expect(s).toContain("--mock-outcome 'incomplete-field-repair-captured-r252'");
    expect(s).toContain("field_repair_group_reason_required_missing");
    // The counts the canonical leg asserts are the R2.54 contract, not the R2.52 one.
    expect(s).toContain("'b[\"fieldRepairMetrics\"][\"fieldRepairOperationCount\"]' '14'");
    expect(s).toContain("'b[\"fieldRepairMetrics\"][\"fieldRepairDependencyGroupCount\"]' '10'");
  });

  it("the canary re-runs the R2.54 acceptance suites, including this test", () => {
    const s = canary();
    for (const suite of [
      "src/domain/foundry/arena-draft/boundaryGroupAlternatives.test.ts",
      "src/domain/foundry/arena-draft/boundaryFieldRepair.test.ts",
      "src/domain/foundry/arena-draft/r252FieldRepairRegression.test.ts",
      "src/domain/foundry/arena-draft/boundaryProhibitedActionCharacterization.test.ts",
      "src/lib/bty/foundry/arena/fieldRepairRouting.contract.test.ts",
      "src/lib/bty/foundry/arena/canonicalAlternativeRunnerBinding.contract.test.ts",
    ]) {
      expect(s, suite).toContain(suite);
    }
  });
});

describe("[R2.54] the preparation path stops before any credential or provider use", () => {
  const canary = (): string => {
    const dir = mkdtempSync(join(tmpdir(), "r254-cred-"));
    try {
      const out = join(dir, "canary.sh");
      execFileSync("npx", ["--yes", "tsx", BOUNDARY_REPLAY_RUNNER_PATH, "--out", out], { cwd: REPO, encoding: "utf8" });
      return readFileSync(out, "utf8");
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  };

  it("`--credential-boundary-check` exits BEFORE the credential is read", () => {
    const s = canary();
    const checkExit = s.indexOf("CREDENTIAL NOT REQUESTED");
    const readsKey = s.indexOf("read -rs LLM_API_KEY");
    expect(checkExit).toBeGreaterThan(0);
    expect(readsKey).toBeGreaterThan(0);
    // Ordering is the proof: the boundary-check exit is reached first, unconditionally.
    expect(checkExit).toBeLessThan(readsKey);
    expect(s).toContain(`if [ "$CHECK_ONLY" = '1' ]; then`);
  });

  it("the runner ITSELF never reads a credential or contacts a provider", () => {
    const src = readFileSync(RUNNER, "utf8");
    for (const forbidden of ["LLM_API_KEY", "OPENAI_API_KEY", "fetch(", "https://api."]) {
      // The generated shell handles the credential; the TypeScript builder must not touch one.
      const builderSource = src.slice(0, src.indexOf("const script = "));
      expect(builderSource, forbidden).not.toContain(forbidden);
    }
  });

  it("the bound preparation mode performs zero generation, database and deployment actions", () => {
    const b = bindingJson();
    expect(b.generationCalls).toBe(0);
    expect(b.broadReviewCalls).toBe(0);
    expect(b.databaseCalls).toBe(0);
    expect(b.deploymentActions).toBe(0);
    expect(b.automaticTransportRetries).toBe(0);
  });
});
