#!/usr/bin/env npx tsx
/**
 * Collate a Practice stability run into the result JSON and the human-review packet
 * (Slice 3.2I-R5B1A.1-R2.23D-R2).
 *
 * Previously this was a `tsx -e` block generated by the shell with `${…}` interpolation — the same
 * construction that hid a top-level-await transform error in the provider preflight until an
 * operator had already entered a credential. It is now a tracked file taking arguments, with no
 * top-level await.
 *
 *   npx tsx scripts/practice-stability-collate.ts --run-id <id> --passes <n> --json <path> --md <path>
 *
 * Reads only the immutable artifacts of the named run. No provider call, no database.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ARTIFACT_DIR, lineageIndex } from "@/lib/bty/foundry/arena/evalArtifact";

type Attempt = { outcome?: string; defectCodes?: string[] };
type Choice = { label: string };
type Result = {
  id: string;
  passId?: string;
  ms?: number;
  ok?: boolean;
  reason?: string;
  attempts?: Attempt[];
  draft?: {
    title: string;
    opening: string;
    primary: { choices: Choice[] };
    tradeoff: { choices: Choice[] };
    actionDecision: { choices: Choice[] };
    branches?: Record<string, { resultingWorldState?: string; escalationText: string; tradeoffChoices: Choice[]; actionDecision: { choices: Choice[] } }>;
  };
};

function arg(name: string, fallback?: string): string {
  const i = process.argv.indexOf(`--${name}`);
  const v = i >= 0 ? process.argv[i + 1] : undefined;
  if (v === undefined) {
    if (fallback !== undefined) return fallback;
    throw new Error(`missing --${name}`);
  }
  return v;
}

function main(): void {
  const runId = arg("run-id");
  const passes = Number(arg("passes", "2"));
  const outJson = arg("json");
  const outMd = arg("md");

  const dir = join(process.cwd(), ARTIFACT_DIR);
  const mine = lineageIndex(dir).filter((e) => e.runId === runId);
  if (mine.length !== passes) {
    throw new Error(`expected ${passes} immutable artifacts for run ${runId}, found ${mine.length}`);
  }

  const payloads = mine.map((e) => JSON.parse(readFileSync(join(dir, e.file), "utf8")) as { passId: string; results: Result[] } & Record<string, unknown>);
  const results: Result[] = payloads.flatMap((p) => p.results.map((r) => ({ ...r, passId: p.passId })));
  const generated = results.filter((r) => r.ok === true);
  // A first-attempt success recorded no ranked gate rejection at all.
  const firstAttempt = generated.filter((r) => (r.attempts ?? []).filter((a) => String(a.outcome ?? "").startsWith("gate_level_")).length === 0);

  const summary = {
    head: payloads[0].head,
    manifestSha256: payloads[0].manifestSha256,
    artifactSchemaVersion: payloads[0].artifactSchemaVersion,
    model: payloads[0].model,
    sampling: payloads[0].sampling,
    artifacts: mine.map((e) => e.file),
    expected: passes * 3,
    executed: results.length,
    generated: generated.length,
    firstAttemptValid: firstAttempt.length,
    retryRecovered: generated.length - firstAttempt.length,
    terminalFailures: results.filter((r) => r.ok === false).length,
    defectFrequency: results
      .flatMap((r) => (r.attempts ?? []).flatMap((a) => a.defectCodes ?? []))
      .reduce<Record<string, number>>((m, c) => ({ ...m, [c]: (m[c] ?? 0) + 1 }), {}),
    latencyMs: results.map((r) => ({ id: r.id, passId: r.passId, ms: r.ms })),
    results,
  };
  writeFileSync(outJson, JSON.stringify(summary, null, 2));

  const lines: string[] = [
    "# R2.23D-R2 Practice stability review",
    "",
    "STRUCTURAL + SEMANTIC GATES: see result JSON",
    "HUMAN PRODUCT REVIEW REQUIRED",
    "",
    `- head: ${summary.head}`,
    `- contract manifest: ${summary.manifestSha256}`,
    `- artifact schema: ${summary.artifactSchemaVersion}`,
    `- model: ${summary.model}`,
    `- immutable artifacts: ${summary.artifacts.join(", ")}`,
    `- expected / executed / generated: ${summary.expected} / ${summary.executed} / ${summary.generated}`,
    `- first-attempt valid: ${summary.firstAttemptValid}   retry-recovered: ${summary.retryRecovered}`,
    "",
  ];
  for (const r of results) {
    lines.push(`## ${r.id} · ${r.passId} · attempts ${(r.attempts ?? []).length + 1}`, "");
    if (!r.ok || !r.draft) {
      lines.push(`REJECTED: ${r.reason ?? "unknown"}`, "");
      continue;
    }
    const d = r.draft;
    lines.push(`**${d.title}**`, "", d.opening, "");
    lines.push("Primary:", ...d.primary.choices.map((c) => `- ${c.label}`));
    lines.push("", "Tradeoff:", ...d.tradeoff.choices.map((c) => `- ${c.label}`));
    lines.push("", "Action:", ...d.actionDecision.choices.map((c) => `- ${c.label}`));
    for (const [k, b] of Object.entries(d.branches ?? {})) {
      lines.push("", `Branch ${k} — ${b.resultingWorldState ?? "(no world state)"}`, `  escalation: ${b.escalationText}`);
      lines.push(...b.tradeoffChoices.map((c) => `  - tradeoff: ${c.label}`));
      lines.push(...b.actionDecision.choices.map((c) => `  - action: ${c.label}`));
    }
    lines.push(
      "",
      "HUMAN REVIEW — every field below is PENDING and must be completed by a person:",
      "- [ ] every option defensible by a competent, well-intentioned person: PENDING",
      "- [ ] no false or vague reassurance at any phase: PENDING",
      "- [ ] confirmed boundary visibly and operationally grounded: PENDING",
      "- [ ] each branch causally distinct from its siblings: PENDING",
      "- [ ] would you put this in front of a learner: PENDING",
      "",
    );
  }
  writeFileSync(outMd, lines.join("\n"));
  process.stdout.write(`wrote ${outJson} and ${outMd}\n`);
}

try {
  main();
} catch (error: unknown) {
  process.stderr.write(`COLLATION FAILED · ${error instanceof Error ? error.message : "unknown"}\n`);
  process.exitCode = 1;
}
