/** @vitest-environment jsdom */
import { describe, it, expect, vi, afterEach } from "vitest";
import { render, screen, fireEvent, cleanup } from "@testing-library/react";
import { readFileSync } from "node:fs";
import { ArenaPracticePlayer } from "./ArenaPracticePlayer";
import type { ArenaScenarioDraft, ScenarioBranch } from "@/domain/foundry/arena-draft/types";

/**
 * ARENA CONSEQUENCE LOOP V1 — the learner sees what their choice caused.
 *
 * MEASURED ON THE SHIPPED PLAYER. `ScenarioBranch` carries four things and the player's branch
 * projection destructured three:
 *
 *     return { escalationText: b.escalationText, tradeoffChoices: …, actionDecision: … };
 *
 * `resultingWorldState` — the branch's own statement of the world the learner's choice produced —
 * was stored, generated by both the model and the template, rendered in the Host preview
 * (`ArenaScenarioPreview.tsx:74`) and never shown to the person who made the choice. So a learner
 * picked "Delay the confirmation calls until after the project" and the next thing they read was
 * "The client becomes increasingly frustrated…", with nothing on screen connecting the two. The
 * causal model existed; the causal LOOP did not.
 *
 * NO CORRECT ANSWER, AND NONE IS ADDED HERE. Arena Practice is judgment → consequence → judgment,
 * not question → answer → explanation. Nothing in this slice scores a choice, marks one as
 * preferred, or explains why BTY would have chosen differently — and `isActionCommitment` stays
 * hidden, which Slice 2.4A.4 removed from the UI precisely because it leaked a preferred option.
 *
 * WHAT IT DOES NOT DO: it does not touch generation, the provider prompt, the gates, the template
 * strings, `selected_path`, or the schema. Some stored consequences are strong ("relationships
 * become strained under pressure") and some are bare restatements ("You checked the facts before
 * saying anything"). Their quality becomes measurable once a real learner has walked one; this
 * build only answers whether the learner gets to see them at all.
 */

const branch = (p: string, world: string | undefined, esc: string, actionPrompt: string): ScenarioBranch => ({
  ...(world === undefined ? {} : { resultingWorldState: world }),
  escalationText: esc,
  tradeoffChoices: [{ id: `${p}_t1`, label: `${p} tradeoff one` }, { id: `${p}_t2`, label: `${p} tradeoff two` }],
  actionDecision: {
    prompt: actionPrompt,
    choices: [{ id: `${p}_a1`, label: `${p} act`, isActionCommitment: true }, { id: `${p}_a2`, label: `${p} narrow`, isActionCommitment: false }],
  },
});

const base = (branches: Record<string, ScenarioBranch>): ArenaScenarioDraft => ({
  title: "Branched",
  opening: "Opening.",
  primary: { choices: [{ id: "primary_1", label: "Choose ONE" }, { id: "primary_2", label: "Choose TWO" }] },
  tradeoff: { escalationText: "SHARED FLAT ESCALATION", choices: [{ id: "ft1", label: "f1" }, { id: "ft2", label: "f2" }] },
  actionDecision: { prompt: "shared prompt", choices: [{ id: "fa1", label: "f", isActionCommitment: true }, { id: "fa2", label: "g", isActionCommitment: false }] },
  branches,
});

/** Both branches carry a consequence — the shape the current generator and template produce. */
const BRANCHED = base({
  primary_1: branch("p1", "WORLD ONE — the calls went out and the room went quiet.", "BRANCH ONE ESCALATION", "BRANCH ONE ACTION"),
  primary_2: branch("p2", "WORLD TWO — the calls waited and the client heard it elsewhere.", "BRANCH TWO ESCALATION", "BRANCH TWO ACTION"),
});

/** A legacy flat scenario: no branches at all, which is 8 of the 9 live drafts. */
const FLAT: ArenaScenarioDraft = {
  title: "Flat",
  opening: "Opening.",
  primary: { choices: [{ id: "primary_1", label: "Choose ONE" }, { id: "primary_2", label: "Choose TWO" }] },
  tradeoff: { escalationText: "SHARED FLAT ESCALATION", choices: [{ id: "ft1", label: "flat tradeoff" }] },
  actionDecision: { prompt: "shared prompt", choices: [{ id: "fa1", label: "flat act", isActionCommitment: true }] },
};

const play = (scenario: ArenaScenarioDraft, choice: string, locale: "en" | "ko" = "en") => {
  render(<ArenaPracticePlayer scenario={scenario} locale={locale} mode="test" onExit={() => {}} />);
  fireEvent.click(screen.getByText(locale === "ko" ? "시작" : "Begin"));
  fireEvent.click(screen.getByText(choice));
};

afterEach(cleanup);

// ---------------------------------------------------------------------------
// T1-T5 · the loop itself
// ---------------------------------------------------------------------------

describe("[Consequence Loop · T1-T5] the learner sees what their choice caused", () => {
  it("T1 the branch's consequence is on screen after the primary choice", () => {
    play(BRANCHED, "Choose ONE");
    expect(screen.getByText("WORLD ONE — the calls went out and the room went quiet.")).toBeTruthy();
  });

  it("T2 the consequence comes BEFORE the escalation, in document order", () => {
    play(BRANCHED, "Choose ONE");
    const world = screen.getByText("WORLD ONE — the calls went out and the room went quiet.");
    const esc = screen.getByText("BRANCH ONE ESCALATION");
    // What changed, then what happens next.
    expect(world.compareDocumentPosition(esc) & Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();
  });

  it("T3 primary 1 gives branch 1's consequence AND branch 1's escalation", () => {
    play(BRANCHED, "Choose ONE");
    expect(screen.getByText("WORLD ONE — the calls went out and the room went quiet.")).toBeTruthy();
    expect(screen.getByText("BRANCH ONE ESCALATION")).toBeTruthy();
  });

  it("T4 primary 2 gives branch 2's consequence AND branch 2's escalation", () => {
    play(BRANCHED, "Choose TWO");
    expect(screen.getByText("WORLD TWO — the calls waited and the client heard it elsewhere.")).toBeTruthy();
    expect(screen.getByText("BRANCH TWO ESCALATION")).toBeTruthy();
  });

  it("T5 no cross-branch bleed — the other branch's consequence is absent on both paths", () => {
    play(BRANCHED, "Choose ONE");
    expect(screen.queryByText("WORLD TWO — the calls waited and the client heard it elsewhere.")).toBeNull();
    expect(screen.queryByText("BRANCH TWO ESCALATION")).toBeNull();
    cleanup();
    play(BRANCHED, "Choose TWO");
    expect(screen.queryByText("WORLD ONE — the calls went out and the room went quiet.")).toBeNull();
    expect(screen.queryByText("BRANCH ONE ESCALATION")).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// T6-T7 · absent field and legacy scenarios
// ---------------------------------------------------------------------------

describe("[Consequence Loop · T6-T7] nothing is invented when there is nothing to show", () => {
  it("T6 a blank or missing consequence renders no surface at all", () => {
    for (const world of [undefined, "", "   "]) {
      const s = base({
        primary_1: branch("p1", world, "BRANCH ONE ESCALATION", "BRANCH ONE ACTION"),
        primary_2: branch("p2", "w2", "BRANCH TWO ESCALATION", "BRANCH TWO ACTION"),
      });
      play(s, "Choose ONE");
      // The escalation still arrives; no label, no empty card, no "undefined".
      expect(screen.getByText("BRANCH ONE ESCALATION")).toBeTruthy();
      expect(screen.queryByText("What happened")).toBeNull();
      expect(screen.queryByText(/undefined/)).toBeNull();
      expect(screen.queryByTestId("practice-consequence")).toBeNull();
      cleanup();
    }
  });

  it("T7 a legacy flat scenario walks exactly as before", () => {
    play(FLAT, "Choose ONE");
    expect(screen.getByText("SHARED FLAT ESCALATION")).toBeTruthy();
    expect(screen.queryByTestId("practice-consequence")).toBeNull();
    fireEvent.click(screen.getByText("flat tradeoff"));
    expect(screen.getByText("shared prompt")).toBeTruthy();
  });
});

// ---------------------------------------------------------------------------
// T8-T12 · what must not appear, and what must not move
// ---------------------------------------------------------------------------

describe("[Consequence Loop · T8-T12] no correct answer, no hidden direction, no new writes", () => {
  it("T8 nothing on the consequence screen scores, ranks or explains a choice", () => {
    play(BRANCHED, "Choose ONE");
    const body = document.body.textContent ?? "";
    /*
      "points" is NOT in this list on purpose: the test banner already says "no points are
      earned", which is the opposite of a score. What must never appear is a verdict.
    */
    for (const banned of ["Correct", "Incorrect", "Best choice", "Good choice", "Wrong", "Recommended", "You should have", "You chose"]) {
      expect(body, banned).not.toContain(banned);
    }
    // The consequence element carries the stored sentence and nothing else.
    expect(screen.getByTestId("practice-consequence").textContent)
      .toBe("WORLD ONE — the calls went out and the room went quiet.");
  });

  it("T9 isActionCommitment is never exposed", () => {
    play(BRANCHED, "Choose ONE");
    fireEvent.click(screen.getByText("p1 tradeoff one"));
    expect(document.body.innerHTML).not.toContain("isActionCommitment");
    expect(document.body.textContent ?? "").not.toContain("commitment");
  });

  it("T10 the Host preview is not the surface this slice changed", () => {
    // ArenaScenarioPreview has rendered the consequence since 3.2I; this build did not touch it.
    const preview = readFileSync("src/components/foundry/arena-practice/ArenaScenarioPreview.tsx", "utf8");
    expect(preview).toContain("branch.resultingWorldState");
  });

  it("T11 selected_path writes are unchanged — the consequence causes no extra write", () => {
    const onPath = vi.fn();
    render(<ArenaPracticePlayer scenario={BRANCHED} locale="en" mode="play" onExit={() => {}} onPath={onPath} onComplete={() => {}} />);
    fireEvent.click(screen.getByText("Begin"));
    fireEvent.click(screen.getByText("Choose ONE"));
    // Exactly one write for the primary selection, with the same payload as before.
    expect(onPath).toHaveBeenCalledTimes(1);
    expect(onPath).toHaveBeenLastCalledWith({ primaryChoiceId: "primary_1" });
    fireEvent.click(screen.getByText("p1 tradeoff two"));
    expect(onPath).toHaveBeenCalledTimes(2);
    expect(onPath).toHaveBeenLastCalledWith({ primaryChoiceId: "primary_1", tradeoffChoiceId: "p1_t2" });
  });

  it("T12 resuming a stored path lands on the same branch, consequence included", () => {
    render(
      <ArenaPracticePlayer
        scenario={BRANCHED}
        locale="en"
        mode="play"
        onExit={() => {}}
        onPath={() => {}}
        onComplete={() => {}}
        initialPath={{ v: 1, primaryChoiceId: "primary_2" }}
      />,
    );
    expect(screen.getByText("WORLD TWO — the calls waited and the client heard it elsewhere.")).toBeTruthy();
    expect(screen.getByText("BRANCH TWO ESCALATION")).toBeTruthy();
    expect(screen.queryByText("WORLD ONE — the calls went out and the room went quiet.")).toBeNull();
  });
});

// ---------------------------------------------------------------------------
// T13-T15 · both languages, and the blast radius
// ---------------------------------------------------------------------------

describe("[Consequence Loop · T13-T15] both languages, stored text verbatim", () => {
  it("T13 a Korean consequence renders exactly as stored, under Korean chrome", () => {
    const KO = base({
      primary_1: branch("p1", "팀 전체에 공개하고 함께 결정하려 했습니다.", "상황이 이어집니다.", "이제 무엇을 하시겠습니까?"),
      primary_2: branch("p2", "먼저 사실부터 확인했습니다.", "다른 상황이 이어집니다.", "이제 무엇을 하시겠습니까?"),
    });
    play(KO, "Choose ONE", "ko");
    expect(screen.getByText("팀 전체에 공개하고 함께 결정하려 했습니다.")).toBeTruthy();
    expect(screen.getByText("그 결과")).toBeTruthy();
    expect(screen.getByText("상황이 더 어려워집니다")).toBeTruthy();
  });

  it("T14 an English consequence renders verbatim under English chrome", () => {
    play(BRANCHED, "Choose ONE");
    expect(screen.getByText("WORLD ONE — the calls went out and the room went quiet.")).toBeTruthy();
    expect(screen.getByText("What happened")).toBeTruthy();
    expect(screen.getByText("It gets harder")).toBeTruthy();
  });

  it("T15 no schema, provider or generation file is involved", () => {
    // The consequence already exists in the type and in stored data; nothing about how it is
    // produced changes here.
    const types = readFileSync("src/domain/foundry/arena-draft/types.ts", "utf8");
    expect(types).toContain("resultingWorldState?: string;");
    const template = readFileSync("src/lib/bty/foundry/arena/arenaScenarioTemplate.ts", "utf8");
    expect(template).toContain('resultingWorldState: "You raised it openly with the whole team."');
  });
});
