// @ts-expect-error Generated by OpenNext immediately before Wrangler bundles this wrapper.
import app from "../.open-next/worker.js";
import { getSupabaseAdmin } from "@/lib/supabase-admin";
import { syncMicrosoftManagers } from "@/lib/bty/foundry/events/microsoftManagerSync.server";

type ExecutionContext = { waitUntil(promise: Promise<unknown>): void };

export default {
  fetch: app.fetch,
  scheduled(_event: unknown, _env: unknown, ctx: ExecutionContext) {
    const admin = getSupabaseAdmin();
    if (!admin) {
      console.error("[microsoft-authority-sync] scheduled admin unavailable");
      return;
    }
    ctx.waitUntil(
      syncMicrosoftManagers(admin).then((result) => {
        console.error("[microsoft-authority-sync] scheduled run", {
          ok: result.ok, complete: result.complete, examined: result.examined,
          managers: result.managers, indeterminate: result.indeterminate, failures: result.failures,
        });
      }),
    );
  },
};
