-- Slice 3.2I-R5B1A.1 — ONE authoritative Practice shell per (owner, training).
--
-- WHY: "Create practice" must be globally atomic across Cloudflare Worker isolates. A
-- SELECT-then-INSERT check is not atomic (two isolates can both observe "none" and both insert).
-- This partial UNIQUE INDEX is the global authority: the second concurrent INSERT for the same
-- (owner_user_id, source_event_id) new-authority relationship is rejected by the database (SQLSTATE
-- 23505), and createOrOpenArenaDraftShell() then loads the winning row — so every caller converges
-- to one canonical draft id and no duplicate/orphan authoritative shell can remain.
--
-- SCOPE (partial, exact relationship): only NEW-AUTHORITY drafts carry
-- guided_answers.practiceSetupVersion (Slice 3.2I-R5A.2). The index constrains exactly those.
--   * Legacy drafts (no discriminator, pre-R5A.2) are NOT constrained — historical legacy
--     duplicates can never block this index.
--   * A legitimate revision UPDATEs the SAME row in place (never a new row), so it never conflicts.
--   * A new training version is a new source_event_id, so it never conflicts.
--   * This table holds only status='draft' rows; published Practices live in a separate table, so
--     publication never creates a second row here.
-- The predicate uses a stored, immutable jsonb expression (guided_answers ->> '...'), which is a
-- valid partial-index predicate under the actual PostgreSQL contract.
--
-- ADDITIVE + IDEMPOTENT: CREATE UNIQUE INDEX IF NOT EXISTS only. No table/column/constraint/RLS/
-- grant/default/backfill change. No row is deleted or merged. Reversible by DROP INDEX.
--
-- DUPLICATE PREFLIGHT — run this READ-ONLY query BEFORE applying (do NOT auto-delete anything):
--
--     select owner_user_id, source_event_id, count(*)
--     from public.foundry_arena_scenario_drafts
--     where (guided_answers ->> 'practiceSetupVersion') is not null
--     group by owner_user_id, source_event_id
--     having count(*) > 1;
--
-- If any group is returned, STOP: a human must resolve those duplicates before the index can be
-- created (CREATE UNIQUE INDEX will otherwise fail). The create-or-open shell path had never been
-- deployed to any environment before this slice, so on staging/production this set is expected to
-- be EMPTY. This migration performs no cleanup.
--
-- ROLLBACK:
--     drop index if exists public.foundry_arena_scenario_drafts_one_shell_idx;

create unique index if not exists foundry_arena_scenario_drafts_one_shell_idx
  on public.foundry_arena_scenario_drafts (owner_user_id, source_event_id)
  where (guided_answers ->> 'practiceSetupVersion') is not null;
