import { CASE_001 } from "@/domain/clinical-reasoning/case001";
export type EncounterIntent="patient_question"|"clinical_exam"|"diagnostic_test"|"imaging_request"|"media_request"|"differential_update"|"diagnosis"|"treatment_decision"|"followup_plan"|"confidence"|"rationale"|"unsupported";
export type EncounterFact={id:string;kind:"patient"|"exam"|"test"|"imaging";aliases:string[];response:string};
export type ClinicalEncounterCaseV2={caseId:string;version:string;chiefComplaint:string;patientFacts:EncounterFact[];objectiveFindings:EncounterFact[];tests:EncounterFact[];media:EncounterFact[];hiddenReference:{rubric:string[];clinicianValidationStatus:"pending"|"validated"}};
const evidence=(id:string)=>CASE_001.evidence.find(e=>e.id===id)!;
const fact=(id:string,kind:EncounterFact["kind"],response?:string):EncounterFact=>{const e=evidence(id);return{id,kind,aliases:[e.label,...e.aliases],response:response??e.result}};
export const CASE_001_ENCOUNTER:ClinicalEncounterCaseV2={caseId:CASE_001.caseId,version:"2.0.0",chiefComplaint:"I fell earlier today and broke my two front teeth.",patientFacts:[fact("trauma-timing","patient","It happened about two hours ago after I fell. I did not lose consciousness."),fact("previous-trauma-treatment","patient"),fact("spontaneous-pain","patient")],objectiveFindings:[fact("fracture-extent","exam"),fact("pulp-exposure","exam"),fact("mobility","exam"),fact("displacement","exam"),fact("probing","exam"),fact("occlusion","exam")],tests:[fact("cold-8","test"),fact("cold-9","test"),fact("cold-control","test"),fact("percussion","test"),fact("palpation","test"),fact("bite-symptoms","test")],media:[fact("radiograph","imaging"),fact("root-fracture","imaging"),fact("alveolar-fracture","imaging")],hiddenReference:{rubric:CASE_001.rubric.criticalEvidenceIds,clinicianValidationStatus:"pending"}};
export type EncounterEventV2={sequence:number;timestamp:string;elapsedMs:number;type:string;doctorMessage?:string;intent?:EncounterIntent;canonicalIds?:string[];response?:string};
export function interpretEncounter(input:string,c=CASE_001_ENCOUNTER){const q=input.toLowerCase();const intent:EncounterIntent=q.startsWith("do you")||q.startsWith("are you")||q.startsWith("when")?"patient_question":q.includes("x-ray")||q.includes("xray")||q.includes("pa")?"imaging_request":q.includes("photo")?"media_request":q.includes("cold")||q.includes("percussion")||q.includes("palpation")||q.includes("probe")?"diagnostic_test":q.includes("mobility")||q.includes("loose")||q.includes("fracture")||q.includes("occlusion")?"clinical_exam":q.includes("diagnos")?"diagnosis":q.includes("treat")?"treatment_decision":q.includes("follow")?"followup_plan":q.includes("differential")?"differential_update":"patient_question";const pool=intent==="imaging_request"||intent==="media_request"?c.media:intent==="clinical_exam"?c.objectiveFindings:intent==="diagnostic_test"?c.tests:c.patientFacts;const ids=(q.includes("when did")?["trauma-timing"]:q.includes("cold")&&q.includes("#8")?["cold-8"]:q.includes("cold")&&q.includes("#9")?["cold-9"]:pool.filter(f=>f.aliases.some(a=>q.includes(a.toLowerCase()))).map(f=>f.id));return {intent,canonicalIds:ids,ambiguous:ids.length===0};}
export function respondToEncounter(input:string,c=CASE_001_ENCOUNTER){const r=interpretEncounter(input,c);if(["diagnosis","treatment_decision","followup_plan","differential_update"].includes(r.intent))return{...r,response:"Your clinical reasoning was recorded."};if(!r.canonicalIds.length)return{...r,response:r.intent==="imaging_request"||r.intent==="media_request"?"No authored clinical image is available for this version.":"I don't know that. Please ask about something I can report or request an examination, test, or image."};const facts=[...c.patientFacts,...c.objectiveFindings,...c.tests,...c.media];return{...r,response:r.canonicalIds.map(id=>facts.find(f=>f.id===id)?.response).join(" ")};}
