"use client";

import React from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { getMessages } from "@/lib/i18n";
import type { Locale } from "@/lib/i18n";
import { LetterCalendar, type LetterCalendarDay } from "@/components/center/LetterCalendar";
import type { DayReflectionResponses } from "@/domain/center/letter";

type LetterItem = {
  id: string;
  body: string;
  reply: string | null;
  locale: string;
  createdAt: string;
  // DECISION6 C2: day_reflection shape (optional — legacy letters omit these).
  type?: "letter" | "reflection" | "day_reflection";
  day?: number | null;
  responses?: DayReflectionResponses | null;
};

/** Local YYYY-MM-DD key (matches LetterCalendar's day matching). */
function dayKey(iso: string): string {
  const d = new Date(iso);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

/**
 * /center/letters — Dear Me letter history. Calendar (M2) wired to the
 * lightweight /api/dear-me/letters/calendar feed (M1) for date dots; the list
 * below shows the selected day's letters (or the full recent list when no day is
 * selected). Bodies come from /api/dear-me/letters (API-only; phantom-safe — the
 * reply text was server-generated by getDearMeReplyTemplate). List markup adapted
 * from the retired DearMeClient history <ul> (deleted 05140389).
 */
export default function LettersClient({ locale }: { locale: string }) {
  const lang = (locale === "ko" ? "ko" : "en") as Locale;
  const t = getMessages(lang).center;
  const isKo = lang === "ko";

  const [entries, setEntries] = React.useState<LetterCalendarDay[]>([]);
  const [letters, setLetters] = React.useState<LetterItem[]>([]);
  const [selectedDate, setSelectedDate] = React.useState<string | null>(null);
  const [loading, setLoading] = React.useState(true);
  const [error, setError] = React.useState<string | null>(null);
  const [expandedId, setExpandedId] = React.useState<string | null>(null);

  // B-2-1: deep-link param + fire-once / pending-scroll refs.
  const searchParams = useSearchParams();
  const dayParam = searchParams.get("day");
  const didDeepLinkRef = React.useRef<string | null>(null);
  const pendingScrollIdRef = React.useRef<string | null>(null);

  React.useEffect(() => {
    let cancelled = false;
    Promise.all([
      fetch("/api/dear-me/letters/calendar", { credentials: "include" })
        .then((r) => (r.ok ? r.json() : null))
        .catch(() => null),
      fetch("/api/dear-me/letters", { credentials: "include" })
        .then((r) => (r.ok ? r.json() : null))
        .catch(() => null),
    ])
      .then(([calData, letterData]) => {
        if (cancelled) return;
        if (Array.isArray(calData?.entries)) setEntries(calData.entries as LetterCalendarDay[]);
        if (Array.isArray(letterData?.letters)) setLetters(letterData.letters as LetterItem[]);
        if (!calData && !letterData) setError(t.letterHistoryError);
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [t.letterHistoryError]);

  // B-2-1: History day-anchor deep-link (?day=N). After letters load, find the matching
  // day_reflection, pre-select its date (calendar/list align), expand it, and queue a
  // scroll. Fire-once per dayParam (didDeepLinkRef) so re-fetches/re-renders never fight
  // the user; re-anchors only if dayParam itself changes.
  React.useEffect(() => {
    if (loading) return;
    if (dayParam == null) return;
    const n = Number(dayParam);
    if (Number.isNaN(n)) return;
    if (didDeepLinkRef.current === dayParam) return;
    const target = letters.find((l) => l.type === "day_reflection" && l.day === n);
    if (!target) return; // unknown/absent day → no-op (a later load may still anchor)
    didDeepLinkRef.current = dayParam;
    setSelectedDate(dayKey(target.createdAt)); // (나)-2 pre-select
    setExpandedId(target.id);
    pendingScrollIdRef.current = target.id;
  }, [loading, letters, dayParam]);

  const visible = selectedDate
    ? letters.filter((l) => dayKey(l.createdAt) === selectedDate)
    : letters;

  // B-2-1: scroll the anchored row into view on the render where it actually exists
  // (after the selectedDate filter above includes it) — guarded by visible.some so it
  // never scrolls to a not-yet-mounted row; clears the pending ref to fire exactly once.
  React.useEffect(() => {
    const id = pendingScrollIdRef.current;
    if (!id || typeof window === "undefined") return;
    if (!visible.some((l) => l.id === id)) return; // target not yet rendered
    const el = document.getElementById(`letter-${id}`);
    if (!el) return;
    pendingScrollIdRef.current = null;
    const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    el.scrollIntoView({ block: "start", behavior: reduce ? "auto" : "smooth" });
  }, [visible]);

  function formatDate(iso: string): string {
    return new Date(iso).toLocaleDateString(isKo ? "ko-KR" : "en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    });
  }

  return (
    <main className="min-h-screen" aria-label={t.calendarTitle}>
      <div className="max-w-xl mx-auto px-4 py-8 sm:py-12 space-y-6">
        <header className="flex items-center justify-between">
          <h1 className="text-2xl font-medium text-dear-charcoal m-0">{t.letterHistoryTitle}</h1>
          <div className="flex items-center gap-2">
            {/* B-2-1: program-return link — only when arrived via ?day=N deep-link. Primary return (left). */}
            {dayParam && /^\d+$/.test(dayParam) && (
              <Link
                href={`/${locale}/train/day/${dayParam}`}
                className="text-xs font-medium text-dear-sage hover:text-dear-charcoal transition-colors rounded-lg border border-dear-sage/30 bg-dear-sage/5 px-3 py-1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-dear-sage"
                aria-label={isKo ? `${dayParam}일차로 돌아가기` : `Back to Day ${dayParam}`}
              >
                ← Day {dayParam}
              </Link>
            )}
            <Link
              href={`/${locale}/center`}
              className="text-xs font-medium text-dear-sage hover:text-dear-charcoal transition-colors rounded-lg border border-dear-sage/30 bg-dear-sage/5 px-3 py-1 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-dear-sage"
              aria-label={isKo ? "Center로 돌아가기" : "Back to Center"}
            >
              ← Center
            </Link>
          </div>
        </header>

        {loading ? (
          <p className="text-sm text-dear-charcoal-soft" aria-busy="true">
            {t.letterHistoryLoading}
          </p>
        ) : error ? (
          <p className="text-sm text-red-600" role="alert">
            {t.letterHistoryError}
          </p>
        ) : (
          <>
            <LetterCalendar
              locale={locale}
              entries={entries}
              selectedDate={selectedDate}
              onSelectDate={(d) => {
                setSelectedDate((prev) => (prev === d ? null : d));
                setExpandedId(null);
              }}
            />

            <section
              role="region"
              aria-label={t.letterHistoryListAria}
              className="space-y-3"
            >
              {selectedDate && (
                <div className="flex items-center justify-between">
                  <span className="text-sm font-medium text-dear-charcoal">{selectedDate}</span>
                  <button
                    type="button"
                    onClick={() => setSelectedDate(null)}
                    className="text-xs text-dear-charcoal-soft hover:text-dear-charcoal underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-dear-sage rounded"
                  >
                    {isKo ? "전체 보기" : "Show all"}
                  </button>
                </div>
              )}

              {visible.length === 0 ? (
                <p className="text-sm text-dear-charcoal-soft m-0">
                  {selectedDate ? t.calendarSelectedEmpty : t.letterHistoryEmpty}
                </p>
              ) : (
                <ul className="space-y-3 list-none p-0 m-0" role="list">
                  {visible.map((item) => {
                    const isOpen = expandedId === item.id;
                    const isReflection = item.type === "day_reflection";
                    const answeredQuestions = isReflection
                      ? (item.responses?.questions ?? []).filter((qa) => qa.a.trim().length > 0)
                      : [];
                    const excerpt =
                      item.body.length > 80 ? item.body.slice(0, 80) + "…" : item.body;
                    return (
                      <li
                        key={item.id}
                        id={`letter-${item.id}`}
                        className="rounded-2xl border border-dear-sage/20 bg-dear-sage/5 overflow-hidden"
                      >
                        <button
                          type="button"
                          onClick={() => setExpandedId(isOpen ? null : item.id)}
                          aria-expanded={isOpen}
                          className="w-full text-left px-4 py-3 cursor-pointer hover:bg-dear-sage/10 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-dear-sage"
                        >
                          <div className="flex items-center justify-between gap-2 mb-1">
                            <time className="text-xs text-dear-charcoal-soft" dateTime={item.createdAt}>
                              {formatDate(item.createdAt)}
                            </time>
                            {isReflection ? (
                              <span className="text-xs font-medium text-dear-sage">
                                {isKo ? `Day ${item.day} 성찰` : `Day ${item.day} reflection`}
                              </span>
                            ) : (
                              <span
                                className={`text-xs font-medium ${
                                  item.reply ? "text-dear-charcoal" : "text-dear-charcoal-soft/60"
                                }`}
                              >
                                {item.reply ? t.letterHistoryReplied : t.letterHistoryNoReply}
                              </span>
                            )}
                          </div>
                          {isReflection && item.responses?.title && (
                            <p className="text-sm font-semibold text-dear-charcoal m-0 mb-0.5">
                              {item.responses.title}
                            </p>
                          )}
                          {!isOpen && (
                            <p className="text-sm text-dear-charcoal leading-relaxed m-0">{excerpt}</p>
                          )}
                        </button>

                        {isOpen && (
                          <div className="px-4 pb-4 space-y-3">
                            {isReflection ? (
                              <>
                                {answeredQuestions.map((qa, i) => (
                                  <div key={i}>
                                    <div className="text-xs font-medium text-dear-charcoal-soft mb-1">
                                      {qa.q}
                                    </div>
                                    <p className="text-sm text-dear-charcoal leading-relaxed whitespace-pre-wrap m-0">
                                      {qa.a}
                                    </p>
                                  </div>
                                ))}
                                <div className="border-t border-dear-sage/20 pt-3">
                                  <div className="text-xs font-medium text-dear-charcoal-soft mb-1">
                                    {isKo ? "오늘의 성찰" : "Today's reflection"}
                                  </div>
                                  <p className="text-sm font-medium text-dear-charcoal leading-relaxed whitespace-pre-wrap m-0">
                                    {item.responses?.finalReflection || item.body}
                                  </p>
                                </div>
                              </>
                            ) : (
                              <>
                                <div>
                                  <div className="text-xs font-medium text-dear-charcoal-soft mb-1">
                                    {isKo ? "편지" : "Letter"}
                                  </div>
                                  <p className="text-sm text-dear-charcoal leading-relaxed whitespace-pre-wrap m-0">
                                    {item.body}
                                  </p>
                                </div>
                                {item.reply && (
                                  <div className="border-t border-dear-sage/20 pt-3">
                                    <div className="text-xs font-medium text-dear-charcoal-soft mb-1">
                                      {t.replyStepTitle}
                                    </div>
                                    <p className="text-sm text-dear-charcoal leading-relaxed whitespace-pre-wrap m-0">
                                      {item.reply}
                                    </p>
                                  </div>
                                )}
                              </>
                            )}
                          </div>
                        )}
                      </li>
                    );
                  })}
                </ul>
              )}

              {!selectedDate && letters.length >= 20 && (
                <p className="text-xs text-dear-charcoal-soft/70 m-0">
                  {isKo
                    ? "최근 20개의 편지만 표시돼요."
                    : "Showing the 20 most recent letters."}
                </p>
              )}
            </section>
          </>
        )}
      </div>
    </main>
  );
}
