name: E2E

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "bty-app/**"
      - ".github/workflows/e2e.yml"
  pull_request:
    paths:
      - "bty-app/**"
      - ".github/workflows/e2e.yml"
